name: Quality Assurance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Ejecución programada cada lunes a las 9:00 AM
  schedule:
    - cron: '0 9 * * 1'
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  accessibility:
    name: Accessibility Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Build del sitio
        run: npm run build

      - name: Ejecutar pruebas de accesibilidad
        run: |
          # Instalamos serve si no está disponible
          npm install --no-save serve
          # Ejecutamos el script de pruebas de accesibilidad que usa la configuración personalizada
          npm run test:a11y

  html-validation:
    name: HTML Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Build del sitio
        run: npm run build

      - name: Validar HTML
        run: |
          # Instalamos html-validator-cli
          npm install -g html-validator-cli
          
          # Validamos el HTML de las páginas generadas
          find dist -name "*.html" -exec html-validator --file {} \;
